### ISSUE TITLE
Digital signature

### ISSUE THREAD

**Issue by super-e** [Samourai-Wallet/whirlpool-gui#13]
Would be nice to have the binaries to download digitally signed for verification.
-E-

**Comment by zeroleak** [comment]
signed binaries are coming soon ;)

**Comment by zeroleak** [comment]
Since 0.9.2 binaries are signed with @SamouraiDev 's key.
CLI signature will be automatically verified by GUI in next release.

See whirlpool-client-cli-0.9.2-run.jar.sig on https://github.com/Samourai-Wallet/whirlpool-client-cli/releases/tag/0.9.2
