### ISSUE TITLE
Tor on windows

### ISSUE THREAD

**Issue by niceguy11** [Samourai-Wallet/whirlpool-gui#14]
Tor fails to connect so it fails to connect to the api so it's not possible to use dojo with windows or tor only

**Comment by satsonsats** [comment]
Same Issue. Windows 10
> Tor fails to connect...

**Comment by bb2k16** [comment]
@niceguy11 @satsonsats would you mind try setting the radio button for Tor to off, and in the proxy box, enter:  `socks://127.0.0.1:9050` (if you are running Tor.exe) or `socks://127.0.0.1:9150` (if you are running Tor browser) and see if that works

**Comment by zeroleak** [comment]
> Same Issue. Windows 10
> 
> > Tor fails to connect...

hi, please send full CLI logs (whirlpool-cli.log) to zeroleak@samourai.io so I can investigate this issue.
Thx

**Comment by zeroleak** [comment]
Sorry for late fix. Tor on Windows should be fixed on cli 0.10.5
Restart GUI to update automatically.
