### ISSUE TITLE
[Privacy enhancement] need to copy the txid of the UTXOs to the clipboard instead of opening explorer

### ISSUE THREAD

**Issue by nickodev** [Samourai-Wallet/whirlpool-gui#17]
Suppose someone doesn't want to giveaway the UTXO's txid to their ISP (since clicking on the txid opens the OXT explorer in clearnet), I believe we need to either have a copy txid icon at the left side of the txid (in each row) or by default copying the txid to the clipboard and ask the users whether they want to open the browser or not.

Or maybe we can show a modal with the txid as qr and have the options to copy to clipboard and open in web explorers as buttons

**Comment by samouraiwallet** [comment]
Good suggestion, we'll try to get this in within the next few releases.

**Comment by nickodev** [comment]
Thank you @pajasevi for the copy to clipboard button. 

I have another suggestion
Suppose the user wants to spend one of their Post mix UTXOs in Samourai-Wallet app; They should do the following:
1- On Whirlpoo-gui: check the derivation path for the selected UTXO
2- On Samourai-Wallet app: go to the troubleshooting section and calculate that path to get the address
3- On Samourai-Wallet app: go to <code>Unspent Outputs - Post mix</code> and find the address

I believe we can eliminate the steps 1 and 2 by showing the address instead of the txid:vout on the Whirlpool-gui UTXO list, then if the user wants to see the transaction on the explorer, they can click on the newly added button and copy its txid into their clipboard

(Not related to Whirlpool-gui project but regarding to step no.3, we need the <code>Spend</code> menu item there, since marking all UTXOs as <code>Do Not Spend</code> and then spend a particular UTXO is a very bad UX practice)

What do you think?

edit: CC @zeroleak @samouraiwallet

**Comment by pajasevi** [comment]
Makes sense to me, that we could show address in some way in the UI.
