### ISSUE TITLE
Connection failed: Failed to fetch

### ISSUE THREAD

**Issue by shamoons** [Samourai-Wallet/whirlpool-gui#2]
I'm setting up a new Whirlpool GUI on Windows 10 and this is what happens when I start it.

![image](https://user-images.githubusercontent.com/1019677/60178542-c46a8480-97e9-11e9-8376-19a3da5e7780.png)

Also, continues even when it's been "2 minutes" or more

**Comment by pxsocs** [comment]
I'm experiencing the same issue on the Mac OS version (same message). 
OS/X gives me a message that Java JDK needs to be installed but even after installing it, the issue persists. 

![Screen Shot 2019-06-26 at 9 21 08 AM](https://user-images.githubusercontent.com/40473443/60179296-c20d2800-97f3-11e9-97f5-8ce2a545f3f3.png)

Form `whirlpool-cli.error.log`:
```
[CLI_LOCAL] => start: java -jar whirlpool-client-cli-0.6.3-run.jar --listen --debug --whirlpool-cli-gui (cwd=[user path]/Library/Application Support/whirlpool-gui)
[ERROR]No Java runtime present, requesting install.
[CLI_LOCAL][ERROR] => terminated with error: 1
```

**Comment by samouraiwallet** [comment]
> I'm setting up a new Whirlpool GUI on Windows 10 and this is what happens when I start it.
> 
> ![image](https://user-images.githubusercontent.com/1019677/60178542-c46a8480-97e9-11e9-8376-19a3da5e7780.png)
> 
> Also, continues even when it's been "2 minutes" or more

Hi @shamoons, please make sure Java is installed and added to PATH and then try relaunching Whirlpool GUI. OpenJDK tends to work smoother than Oracle version of Java. 

@pxsocs - Have you made sure that Java has been added to your PATH? You may need to logout of your user account / reboot before it works.

**Comment by pxsocs** [comment]
Setting the PATH on my side fixed the issue

**Comment by zeroleak** [comment]
Thanks, we will forward CLI errors to GUI in next release.
