### ISSUE TITLE
Errors when changing mix rounds

### ISSUE THREAD

**Issue by dmp1ce** [Samourai-Wallet/whirlpool-gui#22]
I'm getting messages in red when changing the mixing rounds from "1" to "10", like the following:

- "Unexpected end of JSON input"
- "Maximum call stack size exceeded"

I recently updated to version 0.10.0 of the GUI which downloaded 0.10.2 of the CLI. I'm using Arch Linux and a Dojo.

Screenshot attached.
![Screenshot from 2020-01-07 14-43-34](https://user-images.githubusercontent.com/58784/71924543-33437580-315d-11ea-82ac-53cead38fb3f.png)

**Comment by zeroleak** [comment]
thanks, the bug is confirmed and will be fixed quickly.
FYI you can adjust mixing rounds globally in "Configuration > Mixs target min".

**Comment by zeroleak** [comment]
fixed in CLI 0.10.3
