### ISSUE TITLE
MSI Installer fails on Win10 1809

### ISSUE THREAD

**Issue by v0l** [Samourai-Wallet/whirlpool-gui#3]
Hi,

Tried installing the MSI installer and got the following error:

```
Product: whirlpool-gui -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2725. The arguments are: , , 
```

**Comment by zeroleak** [comment]
hi,
it looks like installation from MSI can be very tricky and I'm thinking about disabling msi build.
(see https://github.com/electron/windows-installer/issues/40#issuecomment-198744879)

Did you try to install from .exe?

**Comment by v0l** [comment]
Yep EXE worked fine.

**Comment by zeroleak** [comment]
Thanks :+1:
