### ISSUE TITLE
Better re-mixing balancing

### ISSUE THREAD

**Issue by hbarcelos** [Samourai-Wallet/whirlpool-gui#53]
I'm not sure how the post-mix UTXOs are chosen for a re-mix, but if I leave them unattended, the number of mixes among them can vary wildly.

I try to keep an eye on them and manually select the UTXOs with the least amount of mixes to be the next one, but in a busy day I might end up with something like this:

![image](https://user-images.githubusercontent.com/16565602/184997630-30734f80-fb9b-41bf-9b81-98876f129918.png)

Yesterday the 3 UTXOs at the top (all the same size) were at 15 mixes, today one was mixed 5 additional times, other 2 and the last didn't get lucky.

Would it be possible to make this "select whichever UTXO from the pool with the least amount of mixes to go next" strategy the default, or at least something that users can opt-in?

**Comment by LaurentMT** [comment]
Hey hbarcelos,

Post-mix UTXO submitted for a remix is chosen randomly with all post-mix UTXOs having the same probability to be selected.

The divergence in number of remixes obtained by your postmix UTXOs is expected. The longer your remix your UTXOs, the more these figures will diverge.

While this may be a bit unintuitive, this divergence is actually a good thing. If all your postmix UTXOs had the exact same number of remixes when they're spent, it would be easier for an analyst to determine which UTXOs mixed by Whirlpool are more likely to be related to a given Tx0.

I hope it answers your question.


An unrelated point: This repository is now inactive. The new repository is hosted at https://code.samourai.io/whirlpool/whirlpool-gui
Thanks in advance for posting any issue on the new repository.

**Comment by hbarcelos** [comment]
Yeah, it makes sense.
Thanks for the explanation.
