### ISSUE TITLE
Resource exhaustion after runaway number of java threads

### ISSUE THREAD

**Issue by hkjn** [Samourai-Wallet/whirlpool-gui#7]
With `whirlpool-gui` + CLI version 0.7.0 on Debian 10, I noticed resource exhaustion after running the tool for some hours.

Using `pstree`, I noticed 10000+ java threads:

```
$ watch pstree $(pgrep whirlpool-gui -o)
`-bash---whirlpool-gui-+-java---140*[{java}]
                                    |-whirlpool-gui---whirlpool-gui---19*[{whirlpool-gui}]
                                    |-whirlpool-gui---8*[{whirlpool-gui}]
                                    `-29*[{whirlpool-gui}]
[ ... time passes ... ]
`-bash---whirlpool-gui-+-java---10036*[{java}]
                                    |-whirlpool-gui---whirlpool-gui---16*[{whirlpool-gui}]
                                    |-whirlpool-gui---8*[{whirlpool-gui}]
                                    `-29*[{whirlpool-gui}]
```

The `ps` tool confirms that number of threads grows gradually:
```
$ while true; do ps -AL --no-headers | wc -l; sleep 30; done
1263
[ .. few minutes later .. ]
2426
2424
2456
2470
2506
2530
2564
[ .. some hours later .. ]
11289
11316
11322
-bash: fork: retry: Resource temporarily unavailable
11341
-bash: fork: retry: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: retry: Resource temporarily unavailable
```

Let me know if I can provide any more information on how to debug this.

**Comment by zeroleak** [comment]
Thanks, problem has been identified and will be fixed in next release

**Comment by zeroleak** [comment]
Should be fixed in whirlpool-client-cli 0.7.1 (if using GUI, restart GUI to update automatically)

**Comment by hkjn** [comment]
Thanks for the quick work fixing this!

I can confirm that using whirlpool-client-cli 0.7.1, there does not seem to be any growth in the number of threads with running whirlpool-gui over time. The graph below shows several steep peaks in number of threads when running whirlpool-client-cli 0.7.0, then a roughly constant number of threads after upgrading to 0.7.1:

![whirlpool-thread-growth-fixed](https://user-images.githubusercontent.com/287215/61195443-d1dca580-a6e9-11e9-9bd0-e88a4bcc78e2.png)

**Comment by zeroleak** [comment]
excellent, thanks!
