### ISSUE TITLE
New address

### ISSUE THREAD

**Issue by alcafo** [Samourai-Wallet/whirlpool-gui#9]
Hello.

Using whirlpool-GUI in Ubuntu 18.0.4 when click deposit, after deposit has been confirmed, if click again deposit old address still appearing forcing user to ask for a new address.

This could lead to address reuse if user not pay attention. Samourai wallet android automatically gives you a new address after confirmed deposit, it would be good if it is automatic as it is actually the case in android app.

**Comment by zeroleak** [comment]
This will be fixed in next release

**Comment by zeroleak** [comment]
Fixed in 0.9.1
